name: Sync GitHub Labels

on:
  workflow_dispatch:

jobs:
  sync_labels:
    runs-on: ubuntu-latest

    # This permission is required so the Action can *create/update* labels
    permissions:
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync labels from config
        uses: cssnr/label-creator-action@v1
        with:
          file: labels.json
